#!/usr/bin/php
<?php

namespace Agarithm;

require_once(dirname(dirname(__FILE__))."/Agarithm/Strings.php");
require_once(dirname(dirname(__FILE__))."/Agarithm/Utils.php");

$raw = FILE(dirname(__FILE__)."/trees");

$slopes = [
	[1,1],
	[3,1],
	[5,1],
	[7,1],
	[1,2],
];

$multiple = 1;
foreach($slopes as $slope){
	$trees = 0;
	$dx = $slope[0];
	$dy = $slope[1];
	$x=0;
	$y=0;
	do {
		if($line = trim($raw[$y])){
			$tree = $line[$x] == '#' ? 1 : 0;
			$trees += $tree;
			INFO($line." = ".($tree ? "TREE" : ""));
			$line[$x] = '^';
			$line = Strings::ReplaceAll('.',' ',$line);
			$line = Strings::ReplaceAll('#',' ',$line);
			INFO($line." = ".($tree ? "TREE" : ""));
		}
		$y += $dy;
		$x = ($x+$dx) % strlen($line);

	}while ($y < count($raw));
	$multiple *= $trees;
}

INFO("Trees = $trees");
INFO("multiple = $multiple");
